// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan(arg1:string):Promise<void>;

export function DeleteScan(arg1:string):Promise<void>;

export function ExportReport(arg1:string,arg2:string,arg3:Record<string, any>):Promise<string>;

export function GenerateAIReport(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetAPIKeys():Promise<Record<string, string>>;

export function GetAllScans():Promise<Array<Record<string, any>>>;

export function GetConfig():Promise<Record<string, any>>;

export function GetDashboardStats():Promise<Record<string, any>>;

export function GetScanResult(arg1:string):Promise<Record<string, any>>;

export function GetScanStatus(arg1:string):Promise<Record<string, any>>;

export function GetTrendData(arg1:string):Promise<Record<string, any>>;

export function SaveAPIKey(arg1:string,arg2:string):Promise<void>;

export function SearchScans(arg1:string,arg2:Record<string, any>):Promise<Array<Record<string, any>>>;

export function StartScan(arg1:string,arg2:Record<string, any>):Promise<string>;

export function TestAPIKey(arg1:string,arg2:string):Promise<boolean>;

export function UpdateConfig(arg1:Record<string, any>):Promise<void>;
