// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan(arg1) {
  return window['go']['main']['App']['CancelScan'](arg1);
}

export function DeleteScan(arg1) {
  return window['go']['main']['App']['DeleteScan'](arg1);
}

export function ExportReport(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportReport'](arg1, arg2, arg3);
}

export function GenerateAIReport(arg1, arg2) {
  return window['go']['main']['App']['GenerateAIReport'](arg1, arg2);
}

export function GetAPIKeys() {
  return window['go']['main']['App']['GetAPIKeys']();
}

export function GetAllScans() {
  return window['go']['main']['App']['GetAllScans']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetScanResult(arg1) {
  return window['go']['main']['App']['GetScanResult'](arg1);
}

export function GetScanStatus(arg1) {
  return window['go']['main']['App']['GetScanStatus'](arg1);
}

export function GetTrendData(arg1) {
  return window['go']['main']['App']['GetTrendData'](arg1);
}

export function SaveAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SaveAPIKey'](arg1, arg2);
}

export function SearchScans(arg1, arg2) {
  return window['go']['main']['App']['SearchScans'](arg1, arg2);
}

export function StartScan(arg1, arg2) {
  return window['go']['main']['App']['StartScan'](arg1, arg2);
}

export function TestAPIKey(arg1, arg2) {
  return window['go']['main']['App']['TestAPIKey'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
